- name: Create static IP for app server
  google.cloud.gcp_compute_address:
    name: "{{prefix}}-app-server-static-ip"
    region: "{{gcp_region}}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_credentials_file }}"
    state: present
  register: app_server_static_ip_result


- name: Create app server
  google.cloud.gcp_compute_instance:
    name: "{{prefix}}-app-server"
    machine_type: e2-medium
    zone: "{{gcp_zone}}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{gcp_credentials_file}}"
    tags:
      items:
        - "{{prefix}}-app-server"
    disks:
      - auto_delete: true
        boot: true
        initialize_params:
          source_image: projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2404-noble-amd64-v20250530
          disk_size_gb: 20
    network_interfaces:
      - subnetwork:
          selfLink: "https://www.googleapis.com/compute/v1/projects/{{gcp_project}}/regions/{{gcp_region}}/subnetworks/{{subnet_name}}"
        access_configs:
          - name: External NAT
            nat_ip: "{{ app_server_static_ip_result }}"
            type: ONE_TO_ONE_NAT

