- name: Create allow host ingress firewall rule
  google.cloud.gcp_compute_firewall:
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_credentials_file }}"
    project: "{{ gcp_project }}"
    name: "{{prefix}}-allow-host"
    network:
      selfLink: "https://www.googleapis.com/compute/v1/projects/{{gcp_project}}/global/networks/{{network_name}}"
    direction: INGRESS
    priority: 1000
    allowed:
      - ip_protocol: tcp
        ports:
          - 22
          - 80
          - 8080
          - 443
          - 3000
          - 9090
          - 9001
          - 111
          - 2049
      - ip_protocol: udp
        ports:
          - 111
          - 2049
    source_ranges:
      - "{{ host_ip }}/32"
    state: present

