- name: Download Loki binary on log server
  shell: |
    gcloud compute ssh {{ prefix }}-log-server --zone {{ gcp_zone }}  --command "
      wget -q https://github.com/grafana/loki/releases/download/v2.9.2/loki-linux-amd64.zip && \
      unzip -o loki-linux-amd64.zip && \
      sudo mv loki-linux-amd64 /usr/local/bin/loki && \
      sudo chmod +x /usr/local/bin/loki
    "

